(function(){
'use strict';
const $=s=>document.querySelector(s);
const pageNames={dashboard:'Dashboard',nova:'Nova PMC',rascunhos:'Rascunhos',solicitacoes:'Pedidos',referencias:'Budget',compradora:'Área da Compradora',usuarios:'Usuários',config:'Configurações',detalhe:'Detalhes da PMC'};
const suggestions={dashboard:['Como criar uma PMC?','Como acompanhar meu pedido?','O que significam as cores?'],nova:['Como preencher a Nova PMC?','Como adicionar outro produto?','Para que serve Salvar rascunho?','Como anexar imagem?'],rascunhos:['Como continuar um rascunho?','Rascunho possui número de PMC?'],solicitacoes:['Como abrir uma PMC?','Como pesquisar uma compra?','Posso editar uma PMC enviada?'],referencias:['Como funciona o Budget?','O que são os 90 dias?','O que é GISU?'],compradora:['Como cadastrar orçamentos?','Como devolver para ajuste?','Onde anexar pedido ou NFE?','Como finalizar uma compra?'],usuarios:['Como alterar o perfil de um usuário?','Quais são os perfis do sistema?'],config:['Como configurar o e-mail?','Como funciona a atualização automática?'],detalhe:['Como baixar o PDF da PMC?','Como consultar o histórico?','Como ampliar a imagem do produto?'],default:['Como criar uma PMC?','Como funciona o Budget?','O que é GISU?','Como acompanhar um pedido?']};
const normalize=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
const activePage=()=>document.querySelector('.page.active')?.id||'dashboard';
const profile=()=>normalize($('#mainHeaderUserPerfil')?.textContent||'solicitante');
const firstName=()=>String($('#mainHeaderUserName')?.textContent||'').trim().split(' ')[0];
const escapeHtml=v=>String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function answer(question){
 const q=normalize(question),p=activePage(),pf=profile(),has=(...x)=>x.some(t=>q.includes(normalize(t)));
 if(!q)return 'Digite uma dúvida sobre o funcionamento do PMC Digital.';
 if(has('oi','ola','bom dia','boa tarde','boa noite'))return `Olá${firstName()?', '+firstName():''}! Sou a PMC IA. Posso orientar sobre criação de PMC, Budget, orçamentos, compras, GISU, anexos, status e administração do sistema.`;
 if(has('criar pmc','nova pmc','fazer pmc','solicitacao nova'))return `Para criar uma PMC:\n1. Abra **Nova PMC**.\n2. Preencha os dados gerais.\n3. Selecione a família e informe os produtos.\n4. Preencha a justificativa.\n5. Clique em **Enviar PMC**.\n\nTodos os itens da mesma PMC devem pertencer à mesma família.`;
 if(has('familia','mesma familia'))return 'A família é definida no primeiro produto. Os produtos seguintes recebem automaticamente a mesma família, pois cada PMC deve conter itens de uma única família.';
 if(has('codigo protheus','protheus'))return 'Use o link **Consulta Produto FIEMG**, disponível na tela Nova PMC, para localizar o código Protheus e a descrição correta do material ou serviço.';
 if(has('data necessidade','data da necessidade'))return 'A Data da Necessidade é opcional. Preencha somente quando houver uma data prevista para utilização ou recebimento do produto.';
 if(has('imagem','foto do produto','ampliar','zoom'))return ['compras','admin','gestor'].some(x=>pf.includes(x))?'Abra a PMC e clique na miniatura ou em **Clique para ampliar**. A janela permite aumentar, diminuir e restaurar o zoom, além de arrastar a imagem.':'Na Nova PMC, use o campo **Imagem do produto**. O sistema comprime a imagem automaticamente antes de salvá-la.';
 if(has('rascunho','salvar depois'))return 'O botão **Salvar rascunho** guarda a solicitação sem gerar o número definitivo da PMC. Depois, abra **Rascunhos**, revise os dados e envie quando estiver pronta.';
 if(has('editar pmc','alterar pmc enviada','corrigir pmc'))return 'Uma PMC enviada não pode ser editada normalmente. O solicitante somente poderá alterá-la quando a compradora usar **Devolver para ajuste**. Após a correção, ela é reenviada mantendo o mesmo número.';
 if(has('devolver','ajuste','devolvida'))return 'Na tela de detalhes, a compradora clica em **Devolver para ajuste**, informa claramente o que precisa ser corrigido e confirma. O solicitante verá o motivo, poderá editar e reenviar a mesma PMC.';
 if(has('budget','saldo','limite 3000','r 3000','90 dias'))return 'O Budget mostra o limite móvel por família. Compras finalizadas pela unidade consomem o saldo durante 90 dias contados da data de finalização. A tela exibe utilizado, disponível, última compra e próxima liberação.';
 if(has('gisu','licitacao'))return 'GISU identifica compras realizadas por licitação. A compradora marca a PMC como GISU e informa o valor total realizado. Esse valor aparece no Budget da família, mas não reduz o limite de R$ 3.000,00 da unidade.';
 if(has('orcamento','fornecedor','cotacao'))return 'Em **Atualizar produto**, a compradora cadastra manualmente cada orçamento. Informe fornecedor, quantidade, valor unitário, valor total e link opcional. Use **Adicionar mais um fornecedor** para registrar outros orçamentos.';
 if(has('menor preco','melhor orcamento'))return 'O sistema compara os valores unitários dos orçamentos cadastrados para o produto. Revise os dados antes de registrar o fornecedor utilizado na compra.';
 if(has('nfe','nota fiscal','pedido de compra','anexar pedido'))return 'Abra a PMC, clique em **Atualizar produto** e vá à seção **Compra e entrega**. No campo **Selecionar pedido(s) de compra / NFE**, é possível escolher mais de um arquivo.';
 if(has('status','cores','cor do pedido'))return `Cores do painel:\n• Pendente/Solicitada: vermelho claro\n• Em andamento: amarelo\n• Realizado/Aprovado: azul\n• Comprado/Finalizado: verde\n• Cancelado: laranja claro`;
 if(has('cancelar','cancelado'))return 'Ao cancelar um produto ou uma PMC, o registro permanece no sistema com destaque visual, preservando o histórico.';
 if(has('acompanhar','meu pedido','abrir pmc','pedidos'))return 'No Dashboard ou na página **Pedidos**, localize a PMC e clique em **Abrir PMC**. Os produtos, status, compradora, datas, anexos e histórico aparecem nos detalhes.';
 if(has('pdf','imprimir pmc','baixar pdf'))return 'Abra os detalhes da PMC e clique em **Baixar PDF da PMC**. O arquivo reúne dados gerais, produtos, valores, status, datas e anexos informados.';
 if(has('word','modelo de cotacao','documento de cotacao'))return 'Abra os detalhes da PMC e clique em **Gerar modelo de cotação (.docx)**. O documento também pode ser recriado para PMCs antigas usando os dados atuais.';
 if(has('email','e mail','notificacao','reenviar'))return pf.includes('admin')?'O administrador pode usar **Reenviar PMC por e-mail** nos Pedidos ou nos detalhes. O destinatário é o e-mail da compradora definido em Configurações.':'Ao enviar a PMC, o sistema tenta notificar a compradora por e-mail. O acompanhamento principal deve ser feito pelo Dashboard e pela página Pedidos.';
 if(has('historico','auditoria'))return 'Abra a PMC e clique em **Histórico** para consultar devoluções, reenvios e alterações registradas.';
 if(has('compradora','responsavel'))return 'O nome da compradora responsável é preenchido automaticamente com o usuário logado quando ela atualiza o produto.';
 if(has('entrega','finalizar compra','comprado'))return 'Na atualização do produto, preencha status, data de finalização, valor efetivamente comprado, status da entrega e data da entrega. Depois clique em **Salvar dados deste produto**.';
 if(has('usuario','perfil','solicitante','admin','administrador'))return `Perfis principais:\n• Solicitante: Dashboard, Nova PMC, Rascunhos e Budget.\n• Compradora: cotações, compras e entregas.\n• Administrador: acesso completo, usuários e configurações.`;
 if(has('atualizar versao','cache','nova versao'))return 'Quando houver uma nova versão, aparece **Atualizar agora**. Após o clique, o aviso some, o sistema recarrega os arquivos novos e só volta quando outra versão for publicada.';
 if(has('link onedrive','sharepoint','anexo orcamento'))return 'O link OneDrive/SharePoint é opcional. Use-o quando existir orçamento, especificação ou outro documento armazenado no Drive.';
 if(has('ajuda','o que voce faz','como pode ajudar'))return 'Posso explicar menus, campos, regra dos 90 dias, GISU, criação e devolução de PMC, orçamentos, anexos, NFE, status, e-mails e funções administrativas.';
 const contextual={nova:'Nesta tela, posso orientar sobre dados gerais, família, código Protheus, produtos, imagens, anexos, rascunho e envio.',referencias:'Nesta tela, posso explicar limite de 90 dias, saldo disponível, última compra, próxima liberação e GISU.',compradora:'Nesta tela, posso orientar sobre orçamentos, compra, entrega, NFE, devolução e finalização.',detalhe:'Nesta tela, posso explicar PDF, Word, histórico, devolução, GISU e atualização dos produtos.'};
 return `${contextual[p]||'Não encontrei uma resposta exata para essa pergunta.'}\n\nTente perguntar: **criar PMC**, **Budget**, **GISU**, **orçamento**, **NFE**, **devolver para ajuste**, **status** ou **e-mail**.`;
}
function format(text){return escapeHtml(text).replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>');}
function addMessage(text,who='bot',save=true){const box=$('#pmcAssistantMessages');if(!box)return;const row=document.createElement('div');row.className=`pmc-chat-row ${who}`;row.innerHTML=`<div class="pmc-chat-bubble">${format(text)}</div>`;box.appendChild(row);box.scrollTop=box.scrollHeight;if(save)try{const h=JSON.parse(sessionStorage.getItem('pmc_ai_history')||'[]');h.push({text,who});sessionStorage.setItem('pmc_ai_history',JSON.stringify(h.slice(-20)));}catch(_){}}
function ask(q){q=String(q||'').trim();if(!q)return;addMessage(q,'user');setTimeout(()=>addMessage(answer(q),'bot'),160);}
function updateContext(){const p=activePage(),ctx=$('#pmcAssistantContext'),list=$('#pmcAssistantSuggestions');if(!ctx||!list)return;ctx.textContent=`Ajuda contextual: ${pageNames[p]||'PMC Digital'}`;list.innerHTML=(suggestions[p]||suggestions.default).map(x=>`<button type="button">${escapeHtml(x)}</button>`).join('');list.querySelectorAll('button').forEach(b=>b.onclick=()=>ask(b.textContent));}
function init(){const launcher=$('#pmcAssistantLauncher'),panel=$('#pmcAssistantPanel'),close=$('#pmcAssistantClose'),form=$('#pmcAssistantForm'),input=$('#pmcAssistantInput'),clear=$('#pmcAssistantClear');if(!launcher)return;const open=()=>{panel.hidden=false;launcher.hidden=true;launcher.setAttribute('aria-expanded','true');$('#pmcAssistantBadge').hidden=true;updateContext();setTimeout(()=>input.focus(),70)};const shut=()=>{panel.hidden=true;launcher.hidden=false;launcher.setAttribute('aria-expanded','false')};launcher.onclick=open;close.onclick=shut;form.onsubmit=e=>{e.preventDefault();const q=input.value.trim();if(!q)return;input.value='';input.style.height='auto';ask(q)};input.oninput=()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,90)+'px'};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}};clear.onclick=()=>{sessionStorage.removeItem('pmc_ai_history');$('#pmcAssistantMessages').innerHTML='';addMessage(`Olá${firstName()?', '+firstName():''}! Sou a **PMC IA**. Selecione uma sugestão ou digite sua dúvida.`);updateContext()};let restored=false;try{const h=JSON.parse(sessionStorage.getItem('pmc_ai_history')||'[]');if(h.length){h.forEach(m=>addMessage(m.text,m.who,false));restored=true}}catch(_){}if(!restored)addMessage(`Olá${firstName()?', '+firstName():''}! Sou a **PMC IA**, assistente do PMC Digital. Posso ajudar com criação de PMC, Budget, orçamentos, compras, GISU, anexos e status.`);updateContext();new MutationObserver(updateContext).observe(document.querySelector('main')||document.body,{subtree:true,attributes:true,attributeFilter:['class']});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
